version: '3.9'

services:
  server:
    container_name: server
    build: ./server
    command: npm start
    ports:
      - "4002:3000"
    volumes:
      - ./server:/usr/app
  
  sender:
    container_name: sender
    build: ./envio
    ports:
      - "4001:80"
    volumes:
      - ./envio:/usr/share/nginx/html 