version: '3.9'

services:
  server:
    container_name: server
    build: ./server
    command: npm start
    ports:
      - "4002:3000"
    volumes:
      - ./server:/usr/app
    network_mode: bridge  
  
  sender:
    container_name: sender
    build: ./envio
    ports:
      - "4001:80"
    volumes:
      - ./envio:/usr/share/nginx/html 
    network_mode: bridge  


  receiver:
    container_name: panel
    build: ./painel
    ports:
      - "4003:80"
    volumes:
      - ./painel:/usr/share/nginx/html
    network_mode: bridge  
